# Site
repository: CV-Profesional
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: CV
title: About an Student of Engineering Informatics
email: saulgarcia1203@gmail.com
website: https://github.com/louisy03

# Dark Mode (true/false/never)
darkmode: True

# Social links
#twitter_username: facespics
github_username:  louisy03
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: sir.louisy
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Next Link
  icon: fas fa-globe
  url: https://www.google.com
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content:  # this will include new lines to allow paragraphs
My name's Saul and I'am a Junior and student of Engineering Informatics.\n I have experience in <mark>Web Development</mark> and <mark>Data Bases</mark>. I'm currently learning Cibersecurity and Software Development.\n
  I have experience in <mark>C</mark>, <mark>C++</mark>, <mark>Javascript</mark>, <mark>PHP</mark> and <mark>Python</mark>.I want to learn more about the lenguages and technologies that I use.

content:
  - title: CV # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: My Git Profile
        link: github.com/louisy03
        # link_text: Project Website
        additional_links:
          - title:  Github
            icon: fab fa-github
            url: github.com/louisy03
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          One step per day and seven per week...
        description: | # this will include new lines to allow paragraphs
          I started this repository because I was learning about github and I wanted to share my <mark>CV</mark> with others.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Freelancer
        link: www.cucei.udg.mx
        # link_text: boringcompany.com
        sub_title: Student 5th semester
        caption: Agust 2021 - Present
        quote: >
          I have experience in web development and data bases.
        description: | # this will include new lines to allow paragraphs
            Every day is a new chance to learn something new.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Guadalajara
        caption: Agust 2021 - Present
        sub_title: Student 5th semester of Engineering Informatics
        quote: >
          The new generation of students are the future of the world.
        description: | # this will include new lines to allow paragraphs
          During my time in university I have learned many things, from algorithms, efficiency about algorithms, Cibersecurity, Data bases, web development, etc.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in web development and software development, some of my other interests and hobbies are:
      - Volleyball
      - Gaming
      - Anime
      - [Cats](https://youtu.be/JxS5E-kZc2s)
 
      ![a](/images/frieren.jpg "a")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
